//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
    }
}
